org: chimichami
service: api-s3

provider:
  name: aws
  runtime: python3.12	
  # Default memory size for functions (default: 256MB)
  memorySize: 256
  timeout: 30
  iam:
    role: arn:aws:iam::280415542443:role/LabRole

functions:
  lista_buckets:
    handler: lista_buckets.lambda_handler
    memorySize: 512
    events:
      - http:
          path: /s3/lista-buckets
          method: get
          cors: true
          integration: lambda
  lista_objetos_bucket:
    handler: lista_objetos_bucket.lambda_handler
    events:
      - http:
          path: /s3/bucket/lista-objetos
          method: post
          cors: true
          integration: lambda
  crear_bucket:
    handler: crear_bucket.lambda_handler
    memorySize: 512
    events:
      - http:
          path: /${self:provider.stage}/s3/bucket/create-bucket
          method: post
          cors: true
          integration: lambda
          
  create_directory_bucket:
    handler: create_directory_bucket.lambda_handler
    memorySize: 512
    events:
      - http:
          path: /${self:provider.stage}/s3/bucket/create-directory-bucket
          method: post
          cors: true
          integration: lambda

  subir_archivo_bucket:
    handler: subir_archivo_bucket.lambda_handler
    memorySize: 512
    events:
      - http:
          path: /${self:provider.stage}/s3/bucket/upload-file
          method: post
          cors: true
          integration: lambda
